[package]
name = "zed-curry"
version = "0.0.4"
edition = "2021"
description = "Curry language support for Zed"
repository = "https://github.com/fwcd/zed-curry"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
