id = "curry"
name = "Curry"
version = "0.0.1"
schema_version = 1
authors = ["fwcd"]
description = "Curry language support for Zed"
repository = "https://github.com/fwcd/zed-curry"

[grammars.curry]
repository = "https://github.com/matthesjh/tree-sitter-curry"
commit = "d2c895516233b66e1f8d938fb9335b031c582759"
